### ISSUE TITLE
crypto is not defined

### ISSUE THREAD

**Issue by mixmix** [input-output-hk/atala-prism-apollo#135]
### Is this a regression?

Yes

### Description

I'm running `@atala/prism-wallet-sdk@3.2.0` in Node, and I got this error?

### Please provide the exception or error you saw

```bash
ReferenceError: crypto is not defined
  at protoOf.kv (/home/projects/ssb-atala-prism/node_modules/@atala/apollo/Apollo.js:1734:26)
  at protoOf.jv (/home/projects/ssb-atala-prism/node_modules/@atala/apollo/Apollo.js:1272:45)
  at protoOf.createRandomMnemonics (/home/projects/ssb-atala-prism/node_modules/@atala/apollo/Apollo.js:1577:39)
  at Apollo.createRandomSeed (/home/projects/ssb-atala-prism/node_modules/@atala/prism-wallet-sdk/build/node-cjs/index.cjs:1637:36)
  at createAgent (/home/projects/ssb-atala-prism/create-agent.js:22:23)
```

### Anything else?

Line causing the issue is a piece of code

```js
    return toByteArray_1(crypto.getRandomValues(arr).buffer);
```

**Comment by mixmix** [comment]
Seems like this file:
https://github.com/input-output-hk/atala-prism-apollo/blob/c2bf114fa30b0730c4366f60d980ccd30abfd50e/apollo/src/jsMain/kotlin/io/iohk/atala/prism/apollo/securerandom/SecureRandom.kt#L22

**Comment by mixmix** [comment]
Here's a hack I found in @elribonazo 's `pluto-encrypted` codebase (presumabily covering this case)
```js
// === HACK =======================================
const nodeCrypto = require('crypto')

Object.defineProperty(globalThis, 'crypto', {
  value: {
    getRandomValues: (arr) => nodeCrypto.getRandomValues(arr)
  }
})
```
I think the SDK should run in Node, so maybe this hack gets run conditionally on some environment detection. Like if not in the browser, run this? There's probably a better way to detect if you're in a Node ENV and have access to a library called `crypto`.

Alternatively, use another `randomValues` function from somewhere else

**Comment by goncalo-frade-iohk** [comment]
Hi @mixmix. Thanks for bringing this to us.

I've created a ticket for this and we will take it as high priority and we will update the status in here.

**Comment by hamada147** [comment]
Hi @mixmix,
The issue has been fixed. It will be released in the next version of Wallet SDK.
