### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by FabioPinheiro** [input-output-hk/atala-prism-apollo#153]
### Proposed feature

Add Polymorphism to the Key class

Use the `@JvmStatic` in the companion object
        

### Feature description

Here a list of some things that would be useful:

Have generic types/interface for private keys and for public keys
A private key show extend a public key
A specific private keys should extend the generic private key
A specific public keys should extend the generic public key

The public key should have the following utils methods:
- method to get the curve
- get the compress/encoded format (byte array)
- check point on curve (maybe)
- maybe also get X and get Y 
- create new instance from curve and compress/encoded data
- get PublicKey (java class)
The private key should have the following utils methods:
- get the compress/encoded format (byte array)
- create new instance from curve and compress/encoded data (private)
- get PrivateKey (java class)

WIP

**Comment by mkbreuningIOHK** [comment]
@elribonazo , this is something to work on to unblock Fabio's work on Crypto agility. Is there someone that can work on it?

**Comment by FabioPinheiro** [comment]
I can work on it. I mean I'm not proficient in Kotlin what I want a small things so I'm pretty sure that I can Frankenstein those into existence.
But @hamada147 mentioned he was going to create a PR with most of the stuff that we discussed. (before I created this ticket)

**Comment by FabioPinheiro** [comment]
After talking with @goncalo-frade-iohk @elribonazo we agreed that Apollo would only be cryptographic methods. So we may want to remove functionality instead adding more utilities.

So I will for the same as https://github.com/hyperledger-labs/open-enterprise-agent/pull/958 and create my own warp interface of Apollo.

We also don't want to add the `@JvmStatic` annotation to improve the companion object API at this point.

I'm closing this ticket (cc @hamada147)
